spring.application.name=JobPortal
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=your mongodb uir

USER_FOUND = User has already registered.
USER_NOT_FOUND = User has not registered.
INVALID_CREDENTIALS = Invalid Credentials.
OTP_NOT_FOUND = OTP is expired.
INVALID_OTP = Incorrect OTP.
JOB_NOT_FOUND = Job is not found.
JOB_APPLIED_ALREADY = Job applied already.

#Email Properties
spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = your gmail
#spring.mail.password= akdkcdixsnlkavkh
spring.mail.password=your app password
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true
